### ISSUE TITLE
Broken link in buildVars.py comment

### ISSUE THREAD

**Issue by tddpirate** [nvdaaddons/AddonTemplate#14]
The file mentions, in a comment, the link:
https://bitbucket.org/nvdaaddonteam/todo/raw/master/guidelines.txt
However the link is obsolete.
I was forwarded to: https://github.com/nvdaaddons/DevGuide

**Comment by josephsl** [comment]
Hi, thanks for catching this. I’ll change the link to point to add-on dev guide (this change will apply to all add-ons in existence). Thanks.
