### ISSUE TITLE
Prepare the JSON generation for NV Access add-on datastore

### ISSUE THREAD

**Issue by josephsl** [nvdaaddons/AddonTemplate#22]
Hi,

As NV Access is looking into add-on store proposal, and since some add-ons were registered on the NV Access datastore, it makes sense to prepare the add-ons community by offering a way to generate needed data for the add-on store entry. The store entry is a JSON file that records add-on name/ID, author, version, update channel, SHA256 hash, among other data. Therefore, at the template level, edit SConstruct to generate a template JSON file which must be filled in by authors once add-on package generation completes (some values may require manual editing such as version major.minor.patch/publisher, etc.).

This will be done in the following steps:

1. Enhanced buildVars.py by including fields such as license.
2. Edit SConstruct to generate a template JSON file named the same as add-on package name.

Thanks.

**Comment by nvdaes** [comment]
for me this is good. If I remember well, according to @feerrenroot, one approach for now is to use runcreatejson and runvalidate.bat files available in the addon-datastore and add-on-datastore-validation repos, and I use this approach. This is hard, so I have thought about implementing this via GithubActions, but the template is a good approach too.

**Comment by josephsl** [comment]
Hi, the hardest was obtaining SHA256 value for the add-on package (bundle) and converting minimum and last tested version strings to integers. I intentionally left publisher, add-on URL, and version number undefined in the json file generated by the template, and the json will be named addonName-version.json. I’ll post something tomorrow – testing the json approach with Windows App Essentials. Thanks.

**Comment by nvdaes** [comment]
I think that if we use the runcreatejson is all easy.
Before, I mentioned @feerrenrut but I made a mistake in the name. We
can do whatever we want, but since the store is managed by @NVAccess,
I mention them since if the store doesn't go forward, this work may
not be used or other approaches maybe needed.


2022-10-11 7:24 GMT+02:00, Joseph Lee ***@***.***>:

**Comment by nvdaes** [comment]
Also, since the store requires to create pull request, I'll see your
work on the template and then, if I find more comfortable to use
GitHub Actions to create a branch in the forked add-on-datastore, I'll
use it. But for me the template should include this.
I think about GitHub Actions since the json file itself is not very
useful and people needs to fork the store, at least while pull
requests cannot be created just from issues.

2022-10-11 7:44 GMT+02:00, Noelia Ruiz Martínez ***@***.***>:

**Comment by josephsl** [comment]
Hi, agreed – I’m hoping a form can be created to automate all this… Thanks (experiencing headache after spending hours building 32-bit wheels for wxPython 4.2.0).

**Comment by nvdaes** [comment]
For reference, this is been discussed here:

https://github.com/nvaccess/addon-datastore/pull/37

2022-10-11 8:07 GMT+02:00, Joseph Lee ***@***.***>:

**Comment by feerrenrut** [comment]
This is good news from my perspective. Streamlining the tooling to make the process easier for add-on developers is fantastic.

**Comment by nvdaes** [comment]
Í Imo it would be good to make this from scons to create the .json file,and also to use Github Actions to create a branch in the forked add-on datastore which is needed, and at least people wouldn"t need to fork the addon-datastore-validation repo which contains runvalidate.bat. Anyway I think that it"s good to have the ability to create the json file just from scons. @joseph, if you want you can work in the scons file and I can try to work in Github Actions. In case you prefer to work in both approaches feel free to do it. I have a lot of things to do anyway.

Enviado desde mi iPhone

**Comment by josephsl** [comment]
Hi, I do have a working implementation of SCons json generation – it’ll come in multiple commits as I need to first merge #23, then work on getting manifest data to json and then add store specific fields in separate commits. You’ll see this issue updated with commits soon. Thanks.

**Comment by nvdaes** [comment]
Ok, if needed, I"ll work on github actions to create a branch or pull request in the store. The scons implementation is very important in case some day Github is not used. I will test github actions in my github account, so hopely I won"t create many commits.

Enviado desde mi iPhone

**Comment by josephsl** [comment]
Hi,

Resolved as of SConstruct commit that calls json generator. To use the json generator, add-on authors must specify NV Access add-on store fields in their build vars. After the json file is generate,d one must edit the json file to add proper values for publisher, URL (download link, that is) and add-on version number, then rename the json to major.minor.patch.json. I'll incorporate needed changes in Add-on Updater 22.11 and Windows App Essentials 22.12.

Thanks.

**Comment by nvdaes** [comment]
Í"ll create a PR with github actions to avoid renaming and copying the json file to the store if possible. At least for me is more comfortable if a branch in the forked store is created.

Enviado desde mi iPhone
