### ISSUE TITLE
Remove the generation of the Json

### ISSUE THREAD

**Issue by CyrilleB79** [nvdaaddons/AddonTemplate#36]
When building the add-on, a Json file is generated.

It was useful when the add-on store submission process required it. But now, the submission process only requires to open an issue with an URL pointing to the .nvda-addon file and the generation of the Json is done transparently by the store submission process.

I recommend to remove the generation of the Json from the scons default target. It's up to you if you want to generate the whole code for Json generation or if you want to keep it. But if you keep it, please add a separate target to generate only the .json file, e.g. "scons json"

It's also worth noting that the json is not deleted when running "scons -c".

**Comment by josephsl** [comment]
Hi,

For now json generator will be commented out, with an option for creating a separate scons target for it in the future.

Thanks.

**Comment by CyrilleB79** [comment]
Thanks. That's what I did for my own add-ons.
