### ISSUE TITLE
Doc style sheet: Remove inverted color scheme

### ISSUE THREAD

**Issue by JulienCochuyt** [nvdaaddons/AddonTemplate#4]
The provided `style.css` sets an inverted color scheme on the generated HTML documentations (white writing on black background).

While such a color scheme is preferred for many low vision individuals (including myself), many other have different needs.
Strong contrast scheming should be the result of the user configuration of its computer, applications or magnification software - and not enforced by a document.
The default configuration for Windows and a large majority of applications (including the GUI of NVDA) is dark writing on a light background. If a user has specific needs, it already has to deal with configuration and specialized software.
Imposing an inverted color scheme on a document defeats the inverted color scheme setting on magnification software, resulting in specifically annoying the very users it misleadingly tried to help.

My opinion is that most accessible documents should not impose color scheme at all, thus allowing users to more easily apply any desired settings on their display.

Please consider removing the inverted color scheme on the documentation style sheet, which would be more consistent with the documentation shipped with NVDA.

PR follows.

**Comment by josephsl** [comment]
CC @NVDAEs

**Comment by JulienCochuyt** [comment]
@nvdaes, any thoughts on this issue?

**Comment by nvdaes** [comment]
Yes, your thougths are very reasonable.
Anyway, @feerrenrut  comments are needed to continue the add-on workflow started by @mhameed. After job I will approve this PR.
